<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Results</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">BDS 522 Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Introduction</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="Results.html">Results</a>
</li>
<li>
  <a href="Trimmedresults.html">Trimmed Results</a>
</li>
<li>
  <a href="Conclusions.html">Conclusions</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Results</h1>

</div>


<pre><code>## 
## Call:
## lm(formula = RT ~ Age * Treatment, data = FullRTSet)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.235 -2.567 -0.774  2.211 33.773 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              10.674104   1.855415   5.753 5.13e-08 ***
## Age                      -0.014723   0.064049  -0.230   0.8185    
## TreatmentDepletion       -5.055791   2.675636  -1.890   0.0608 .  
## TreatmentInteraction     -5.335375   2.648238  -2.015   0.0458 *  
## TreatmentMWR             -4.177940   2.849864  -1.466   0.1448    
## Age:TreatmentDepletion    0.130076   0.091406   1.423   0.1569    
## Age:TreatmentInteraction  0.073794   0.089485   0.825   0.4109    
## Age:TreatmentMWR          0.005886   0.103262   0.057   0.9546    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.759 on 143 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.1253, Adjusted R-squared:  0.08249 
## F-statistic: 2.926 on 7 and 143 DF,  p-value: 0.006825</code></pre>
<p>Interpreting the results we can see that the average response time in the Baseline Treatment with a predicted age of zero is 10.674 seconds. For each additional year, the response time decreases by -0.014. In the Depletion Treatment, the expected response time decreases by 5.055 seconds, the Interaction Treatment by -5.335, and MWR by 4.177 seconds. This is surprising considering the intuition that people who have a depleted ego might be slower to respond, however, baseline is clearly the highest response time. There is a significant effect seen in the Interaction Treatment with a p-value of 0.0458. From this we can conclude that the effect of the Interaction Treatment alone has a significant impact on response time. Note however that the Depletion Treatment has a p-value of 0.0608, indicating a strong directional effect, though insignificant at the 5% level.</p>
<p>Moving onto the interactions, there were no significant results between age and the treatment conditions for response time. The greatest effect is in the age and depletion treatment with a p-value of 0.1569, however, it doesn’t reach a threshold that would allow us to state with confidence that there is an interaction between the two variables.</p>
<p><img src="Results_files/figure-html/unnamed-chunk-2-1.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-2-2.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-2-3.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-2-4.png" width="672" /></p>
<p>Looking at the supplemental graphs, the residual vs. fitted graph indicates there isn’t non-linear relationship that could have been missed by the initial analysis. The data points are approximately normally distributed as evidenced by the Normal Q-Q graph. However, this is where the outlier discussed earlier appears as plot number 22, which deviates a great deal. The scale-location plot does reveal some clustering along the range of predictors, however, the horizontal line indicates a generally equal variance. The residuals vs. leverage graph shows that while data point twenty-two is extreme, it isn’t influential enough to be in the region of Cook’s distance.</p>
<p>Below the data is analyzed with the assumption that the effect of age is the same regardless of the condition.</p>
<pre><code>## 
## Call:
## lm(formula = RT ~ Age + Treatment, data = FullRTSet)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.054 -2.565 -0.674  2.217 34.189 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           9.17862    1.17192   7.832 9.04e-13 ***
## Age                   0.04205    0.03351   1.255 0.211610    
## TreatmentDepletion   -1.56981    1.08329  -1.449 0.149451    
## TreatmentInteraction -3.37273    1.10561  -3.051 0.002714 ** 
## TreatmentMWR         -3.95191    1.09096  -3.622 0.000402 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.751 on 146 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.1099, Adjusted R-squared:  0.08552 
## F-statistic: 4.507 on 4 and 146 DF,  p-value: 0.001838</code></pre>
<p>The predicted response time in the Baseline Treatment with a predicted age of zero is 9.179 seconds. With each added year there is a .042 increase in response time in the Baseline Treatment. While there is a decrease in predicted response time by 1.57 seconds, it fails to reach significance (p-value = .15) There are, however, statistically significant results in the Interaction and Moral Wiggle Room Treatments with p-values of .002 and .0004 respectively. From this we can conclude that in the Interaction Treatment, response time is predicted to decrease by 3.372 seconds and 3.952 seconds in the Moral Wiggle Room Treatments.</p>
<p><img src="Results_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-4-2.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-4-3.png" width="672" /><img src="Results_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<p>Comparing the outputs to the graphs above, there is little change. However, there is slightly less clustering in the residuals vs. fitted and the scale-location data points.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
